# -*- coding: utf-8 -*-
"""exercicio-lista-arrays3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lC-DBfFI3IxcTeXAFvfTzu_Jtqalk3Up

Declare dois arrays, cada um com um mínimo de cinco elementos, e imprima eles no terminal usando o comando print(). O primeiro array deve conter os produtos de uma loja da sua escolha (loja de comida, materiais de construção, música, etc). O segundo array deve conter os anos de nascimento de familiares e amigos seus. Lembre-se de usar nomes descritivos para nomear cada variável, e de usar o tipo de dado apropriado para cada lista (strings, booleanos, números inteiros, floats).
"""

produtos_liquidos = ["Refrigerante",  "Suco", "Drink Alcoólico", "Cerveja", ]
nome_familia_amigos = ["Mãe", 1982, "Pai", 1984, "parente_proximo", 1994, "amigo1", 1992, "amigo2", 1998]

print(produtos_liquidos)
print(nome_familia_amigos)
print(type(produtos_liquidos))
print(type(nome_familia_amigos))