# -*- coding: utf-8 -*-
"""impressao_andar_vinteandares.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LX8v_WttDc_oL13mf26qJl4rGqb60u14
"""

for andar in range(20,-1,-1):
  if (andar == 13):
      continue
  print("Este é o andar n°: ", str(andar))