# -*- coding: utf-8 -*-
"""teste pyton.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Xw5sOfaR5IDr9vMftp0oiC5fhKBAqJYV
"""

for i in range(5,-1,-1):
  print("Molhe a planta número ", str(i))

for i in range(5,-1,-1):
  if i%2 == 0:
    print("Molhe a planta número", i)

for i in range(0,2):
  planta = str(i)
  print("Molhe as plantinhas", str(i))

n1 = 5
n2 = 6



x=n1*n2
print (x)

n1=(int(input("Digite um número: ")))
contador = n1
for contador in range(0, 11):
    print("A tabuaba de", n1, "é", n1*contador)

def multiplicacao(num1,num2):
  res =  num1 * num2
  return res

num1=int(input("digite um número: "))
num2 = 10

for num2 in range(11):

  print(f'{num1} * {num2} = {multiplicacao(num1,num2)}')

for andar in range(20,-1,-1):
  if (andar == 13):
      continue
  print("Este é o andar n°: ", str(andar))