# -*- coding: utf-8 -*-
"""exercício_CalculadoraInfinita.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ErP5HGCojG_dgZkwt3ZL_91YVV5mzXNH

Faça uma função calculadora que os números e as operações serão feitas pelo usuário. O código deve ficar rodando infinitamente até que o usuário escolha a opção de sair. No início, o programa mostrará a seguinte lista de operações:

1: Soma
2: Subtração
3: Multiplicação
4: Divisão
0: Sair

Digite o número para a operação correspondente e caso o usuário introduza qualquer outro, o sistema deve mostrar a mensagem “Essa opção não existe” e voltar ao menu de opções.

Após a seleção, o sistema deve pedir para o usuário inserir o primeiro e segundo valor, um de cada. Depois precisa executar a operação e mostrar o resultado na tela. Quando o usuário escolher a opção “Sair”, o sistema irá parar.

É necessário que o sistema mostre as opções sempre que finalizar uma operação e mostrar o resultado.
"""

def calculadora():
  try:
    op=0
    print("Calculadora de DOIS números!")
    while op != 5:
      print("Escolha dois números e uma operação: ")
      num1=int(input("Digite o 1° número: "))
      num2=int(input("Digite o 2° número: "))
      op=int(input("1: soma/ 2: subdivisão: 3: multiplicação/ 4: divisão/5: sair: "))

      if op ==1:
        op=num1+num2
      elif op ==2:
        op=num1-num2
      elif op ==3:
        op=num1*num2
      elif op ==4:
        op=num1/num2
      elif op ==5:
        print("Fim Calculadora!")
        break
      print("O resultado da operação é: ", op)
  except:
    print("Apenas números de 1 à 5!")

calculadora()