# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1J0PoAyRyuKA50o19JjDh6xK7x57oHD2C
"""

mesas = [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37]
mesas_quadradas_grandes = [ mesas[8], mesas[11], mesas[14], mesas[25], mesas[26], mesas[27], mesas[28], mesas[29], mesas[30]]
mesas_quadradas_pequenas = [ mesas[2], mesas[3], mesas[4], mesas[5], mesas[6], mesas[10], mesas[24], mesas[31], mesas[32], mesas[33], mesas[34], mesas[35], mesas[36]]
lotado = False

import array
def reserva():
 while lotado == False:
  try:
    reserva=int(input("ESCOLHA SUA RESERVA:"))
    if reserva == 8 or 11:
      print("RESERVA MESA GRANDE NÚMERO: ", reserva)
    elif reserva > 37:
      print("Dentro do Salão apenas até a mesa 37.")
    elif reserva == 17 or 18:
      print("Desculpa, não temas essas mesas.")
    print("Sua reserva é o número: ", reserva)
    mesas.remove(reserva)
    print("Mesas Restantes:")
    for i in range(len(mesas)):
      return mesas
  except:
    print("Apenas NÚMEROS na seleção de RESERVA.")

print(mesas_quadradas_grandes)
print(mesas_quadradas_pequenas)

print("Escolha uma das mesas para continuar sua reserva:")
print("MESAS REDONDAS MÉDIAS:", mesas[12], mesas[16], mesas[19], mesas[20],)
print("MESAS REDONDAS BAIXAS:", mesas[15],)
print("MESAS OVAIS BAIXAS:", mesas[1], mesas[9], mesas[13], mesas[21], mesas[22], mesas[23])
print("MESAS QUADRADAS BAIXAS:", mesas[7],)
print("*SEM MESA*", mesas[17], mesas[18],)