# -*- coding: utf-8 -*-
"""exercicio-nome-usuario-idade-atual

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Kld2d3tAlC7eBuGRMfTs9qlhY6MdaXsy

Desenvolva um programa que recebe do usuário nome completo e ano de nascimento que seja entre 1922 e 2021.
A partir dessas informações, o sistema mostrará o nome do usuário e a idade que completou, ou completará, no ano atual (2022).

Caso o usuário não digite um número ou apareça um inválido no campo do ano, o sistema informará o erro e continuará perguntando até que um valor correto seja preenchido.
"""

def idade():
    infos=True
    while (infos==True):
      try:
        nome_completo=(input("Digite o NOME COMPLETO: "))
        idade=int(input("Digite seu ano de Nascimento: "))
        if idade >= 1922 and idade <=2022:
          idade = 2022 - idade
          print("Nome Completo: ", nome_completo)
          print("Idade em 2022: ", idade)
        elif idade <= 1921 or idade >= 2023:
          if idade <= 1921:
            print("Mais de 100 anos, parabéns!")
            idade()
          if idade <= 1891:
            print("Porém, acho que sabemos que essa idade não é possível atualmente...")
            idade()
          else:
            print("Sei que tecnologia é legal, mas parece que você acabou de nascer...ou ainda vai nascer...")
            idade()
        infos=False
      except:
        print("Apenas número no ano de nascimento, desculpe...")

idade()